# Generated by Django 3.1.5 on 2021-01-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20210119_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crudproject',
        ),
    ]
